(() => {
  'use strict';
  if (typeof map==='undefined'||typeof L==='undefined')return;
  const params=new URLSearchParams(location.search),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const desired={enabled:params.get('compare')==='swipe',left:params.get('left')||'',right:params.get('right')||'',split:clamp(Number(params.get('split'))||50,5,95)};
  const CURRENT='https://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Imagery/MapServer/tile/{z}/{y}/{x}',MIN_OVERLAP=.08;
  let allSources=[],sources=[],imageryEpochs=[],localAoi=null,leftLayer=null,rightLayer=null,dragging=false,dragWas=true,raf=0,rebuildTimer=null;

  function styles(){if(document.getElementById('compareStylesV2'))return;const s=document.createElement('style');s.id='compareStylesV2';s.textContent=`.compareGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.compareActions{display:flex;gap:8px;margin-top:8px}.compareBtn{flex:1;min-height:40px;border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:9px;cursor:pointer}.compareBtn:disabled{opacity:.5}.compareDivider{display:none;position:absolute;z-index:590;top:0;bottom:0;width:34px;margin-left:-17px;cursor:ew-resize;touch-action:none}.compareDivider:before{content:'';position:absolute;left:16px;top:0;bottom:0;width:2px;background:#fff;box-shadow:0 0 0 1px rgba(0,0,0,.45),0 0 12px rgba(0,0,0,.5)}.compareHandle{position:absolute;left:4px;top:50%;transform:translateY(-50%);width:26px;height:48px;border-radius:13px;background:rgba(15,23,32,.95);border:1px solid rgba(255,255,255,.85);display:flex;align-items:center;justify-content:center;color:#fff}.compareLabel{display:none;position:absolute;z-index:580;bottom:18px;max-width:42%;padding:7px 9px;border-radius:8px;background:rgba(15,23,32,.92);border:1px solid var(--line);color:var(--text);font-size:12px;pointer-events:none;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.compareLabel.left{left:12px}.compareLabel.right{right:12px;text-align:right}.compareActive .compareDivider,.compareActive .compareLabel{display:block}@media(max-width:760px){.compareGrid{grid-template-columns:1fr}.compareLabel{bottom:10px;max-width:45%;font-size:11px}}`;document.head.appendChild(s);}
  const opt=(sel,v,t)=>{const o=document.createElement('option');o.value=v;o.textContent=t;sel.appendChild(o);};
  function ui(){const panel=document.getElementById('layerPanel');if(!panel||document.getElementById('compareEnabled'))return;const g=document.createElement('div');g.className='layerGroup';g.id='compareGroup';g.innerHTML=`<h3>Swipe comparison</h3><label class="layerRow"><input type="checkbox" id="compareEnabled" disabled><span class="layerText"><b>Enable comparison</b><small>Left layer stays underneath; drag the divider to reveal the right layer.</small></span></label><div class="compareGrid"><div><label for="compareLeft">Left</label><select class="search" id="compareLeft" disabled></select></div><div><label for="compareRight">Right</label><select class="search" id="compareRight" disabled></select></div></div><div class="compareActions"><button type="button" class="compareBtn" id="compareSwap" disabled>⇄ Swap</button></div><div class="layerOpacity"><label for="compareSplit"><span>Divider</span><span id="compareSplitValue">${desired.split}%</span></label><input class="range" id="compareSplit" type="range" min="5" max="95" step="1" value="${desired.split}"></div><div id="compareStatus" class="layerStatus warn">Loading comparison sources…</div>`;panel.appendChild(g);
    const wrap=document.querySelector('.mapWrap'),d=document.createElement('div');d.id='compareDivider';d.className='compareDivider';d.innerHTML='<div class="compareHandle">↔</div>';const ll=document.createElement('div');ll.id='compareLeftLabel';ll.className='compareLabel left';const rr=document.createElement('div');rr.id='compareRightLabel';rr.className='compareLabel right';wrap.append(d,ll,rr);
    const enabled=document.getElementById('compareEnabled'),left=document.getElementById('compareLeft'),right=document.getElementById('compareRight'),split=document.getElementById('compareSplit');enabled.checked=desired.enabled;
    enabled.addEventListener('change',apply);left.addEventListener('change',apply);right.addEventListener('change',apply);split.addEventListener('input',()=>{document.getElementById('compareSplitValue').textContent=`${split.value}%`;scheduleClip();});document.getElementById('compareSwap').addEventListener('click',()=>{const a=left.value;left.value=right.value;right.value=a;apply();left.dispatchEvent(new Event('change',{bubbles:true}));right.dispatchEvent(new Event('change',{bubbles:true}));});
    const fromPointer=e=>{const r=map.getContainer().getBoundingClientRect(),pct=clamp((e.clientX-r.left)/Math.max(1,r.width)*100,5,95);split.value=String(Math.round(pct));split.dispatchEvent(new Event('input',{bubbles:true}));};
    d.addEventListener('pointerdown',e=>{dragging=true;dragWas=map.dragging.enabled();d.setPointerCapture?.(e.pointerId);if(dragWas)map.dragging.disable();fromPointer(e);e.preventDefault();});d.addEventListener('pointermove',e=>{if(dragging)fromPointer(e);});const stop=e=>{if(!dragging)return;dragging=false;d.releasePointerCapture?.(e.pointerId);if(dragWas)map.dragging.enable();};d.addEventListener('pointerup',stop);d.addEventListener('pointercancel',stop);
  }
  function source(id){return sources.find(s=>s.id===id);}
  function create(s,pane){const l=L.tileLayer(s.url,{minZoom:s.minZoom||0,maxZoom:s.maxZoom||20,maxNativeZoom:s.maxNativeZoom||20,opacity:1,pane,updateWhenZooming:true,keepBuffer:3,attribution:s.attribution||'NSW Spatial Services'});l.on('loading load tileload tileerror',scheduleClip);return l;}
  function clear(){for(const l of [leftLayer,rightLayer]){if(!l)continue;const c=l.getContainer?.();if(c){c.style.clip='';c.style.clipPath='';}l.off('loading load tileload tileerror',scheduleClip);if(map.hasLayer(l))map.removeLayer(l);}leftLayer=rightLayer=null;}
  function scheduleClip(){if(raf)cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{raf=requestAnimationFrame(clipRight);});}
  function clipRight(){raf=0;const enabled=document.getElementById('compareEnabled');if(!enabled?.checked||!rightLayer)return;const pct=clamp(Number(document.getElementById('compareSplit')?.value||50),5,95)/100,size=map.getSize(),nw=map.containerPointToLayerPoint([0,0]),se=map.containerPointToLayerPoint(size),x=nw.x+pct*(se.x-nw.x),c=rightLayer.getContainer?.();if(c)c.style.clip=`rect(${nw.y}px, ${se.x}px, ${se.y}px, ${x}px)`;const lc=leftLayer?.getContainer?.();if(lc)lc.style.clip='';const d=document.getElementById('compareDivider');if(d)d.style.left=`${pct*100}%`;}
  function apply(){const enabled=document.getElementById('compareEnabled'),ls=document.getElementById('compareLeft'),rs=document.getElementById('compareRight'),st=document.getElementById('compareStatus'),wrap=document.querySelector('.mapWrap');clear();wrap?.classList.toggle('compareActive',!!enabled?.checked);if(!enabled?.checked){st.className='layerStatus ready';st.textContent=`${sources.length} comparison sources available here`;return;}const a=source(ls.value),b=source(rs.value);if(!a||!b){st.className='layerStatus warn';st.textContent='Choose an available source for both sides.';return;}leftLayer=create(a,'compareLeft').addTo(map);rightLayer=create(b,'compareRight').addTo(map);document.getElementById('compareLeftLabel').textContent=a.label;document.getElementById('compareRightLabel').textContent=b.label;st.className=a.id===b.id?'layerStatus warn':'layerStatus ready';st.textContent=a.id===b.id?'Both sides use the same source.':`${a.label} ↔ ${b.label}`;scheduleClip();}
  function lonLatToTile(lng,lat,z){const n=2**z,cl=Math.max(-85.05112878,Math.min(85.05112878,lat)),x=Math.floor((lng+180)/360*n),r=cl*Math.PI/180,y=Math.floor((1-Math.asinh(Math.tan(r))/Math.PI)/2*n);return[Math.max(0,Math.min(n-1,x)),Math.max(0,Math.min(n-1,y))];}
  function gridAvailable(g){if(!g||!Number.isInteger(g.level)||typeof g.bits!=='string'||g.bits.length<g.width*g.height)return null;const b=map.getBounds(),[l,t]=lonLatToTile(b.getWest(),b.getNorth(),g.level),[r,bt]=lonLatToTile(b.getEast(),b.getSouth(),g.level),total=Math.max(1,(r-l+1)*(bt-t+1));let available=0;for(let y=Math.max(t,g.top);y<=Math.min(bt,g.top+g.height-1);y++)for(let x=Math.max(l,g.left);x<=Math.min(r,g.left+g.width-1);x++)if(g.bits[(y-g.top)*g.width+(x-g.left)]==='1')available++;const c=map.getCenter(),[cx,cy]=lonLatToTile(c.lng,c.lat,g.level),gx=cx-g.left,gy=cy-g.top,centre=gx>=0&&gy>=0&&gx<g.width&&gy<g.height&&g.bits[gy*g.width+gx]==='1';return centre||available/total>=MIN_OVERLAP;}
  function bboxAvailable(b){if(!Array.isArray(b)||b.length!==4)return false;const v=map.getBounds(),c=map.getCenter(),inter=Math.max(v.getWest(),b[0])<Math.min(v.getEast(),b[2])&&Math.max(v.getSouth(),b[1])<Math.min(v.getNorth(),b[3]);return inter&&(c.lng>=b[0]&&c.lng<=b[2]&&c.lat>=b[1]&&c.lat<=b[3]);}
  const historicAvailable=e=>{const g=gridAvailable(e.coverageGrid);return g===null?bboxAvailable(e.bbox):g;};
  const localAvailable=()=>localAoi?bboxAvailable([localAoi.xmin,localAoi.ymin,localAoi.xmax,localAoi.ymax]):false;
  function rebuild(preserve=true){const l=document.getElementById('compareLeft'),r=document.getElementById('compareRight');if(!l||!r)return;const pl=preserve?l.value:desired.left,pr=preserve?r.value:desired.right,hids=new Set(imageryEpochs.filter(historicAvailable).map(e=>`imagery:${e.year}`)),localOk=localAvailable();sources=allSources.filter(s=>s.kind!=='historic'||hids.has(s.id)).filter(s=>s.kind!=='lidar'||localOk);for(const sel of[l,r]){sel.innerHTML='';const aerial=document.createElement('optgroup');aerial.label='Aerial imagery';sources.filter(s=>s.kind==='current'||s.kind==='historic').forEach(s=>opt(aerial,s.id,s.label));sel.appendChild(aerial);const lidar=document.createElement('optgroup');lidar.label='Local LiDAR hillshade';sources.filter(s=>s.kind==='lidar').forEach(s=>opt(lidar,s.id,s.label));sel.appendChild(lidar);}const oldest=sources.filter(s=>s.kind==='historic').sort((a,b)=>a.year-b.year)[0],defL=oldest?.id||'imagery:current',defR=sources.some(s=>s.id==='imagery:current')?'imagery:current':(sources[0]?.id||'');l.value=source(pl)?pl:defL;r.value=source(pr)?pr:defR;l.disabled=r.disabled=sources.length<2;const en=document.getElementById('compareEnabled'),sw=document.getElementById('compareSwap');en.disabled=sw.disabled=sources.length<2;if(desired.enabled&&!en.disabled)en.checked=true;document.getElementById('compareStatus').textContent=`${sources.length} comparison sources available here${localOk?' • local LiDAR available':''}`;apply();}
  async function load(){const st=document.getElementById('compareStatus');try{const [ir,lr]=await Promise.allSettled([fetch('/lidar/imagery.json?'+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('imagery catalogue'))),fetch('/lidar/status.json?'+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('LiDAR status')))]),im=ir.status==='fulfilled'?ir.value:{epochs:[]},li=lr.status==='fulfilled'?lr.value:{};imageryEpochs=(im.epochs||[]).filter(e=>e.tileUrl);localAoi=li.aoi||null;allSources=[{id:'imagery:current',kind:'current',year:9999,label:'Current NSW aerial imagery',url:CURRENT,maxNativeZoom:18,attribution:'© State of New South Wales (Spatial Services)'}];imageryEpochs.forEach(e=>allSources.push({id:`imagery:${e.year}`,kind:'historic',year:Number(e.year),label:`${e.year} aerial — ${e.title||'NSW historical imagery'}`,url:e.tileUrl,maxNativeZoom:20,attribution:'© State of New South Wales (Spatial Services historical imagery)'}));if(li.layers?.hillshade?.available)allSources.push({id:'lidar:latest',kind:'lidar',year:9999,label:'Latest local LiDAR hillshade',url:'/lidar/hillshade/{z}/{x}/{y}.png',minZoom:9,maxNativeZoom:17});Object.entries(li.epochLayers||{}).filter(([,v])=>v?.hillshade?.available).sort(([a],[b])=>+a-+b).forEach(([y])=>allSources.push({id:`lidar:${y}`,kind:'lidar',year:+y,label:`${y} local LiDAR hillshade`,url:`/lidar/epochs/${y}/hillshade/{z}/{x}/{y}.png`,minZoom:9,maxNativeZoom:17}));rebuild(false);}catch(e){st.className='layerStatus warn';st.textContent=`Comparison sources unavailable: ${e.message}`;}}
  styles();ui();if(!map.getPane('compareLeft'))map.createPane('compareLeft');if(!map.getPane('compareRight'))map.createPane('compareRight');map.getPane('compareLeft').style.zIndex=500;map.getPane('compareRight').style.zIndex=510;map.getPane('compareLeft').style.pointerEvents='none';map.getPane('compareRight').style.pointerEvents='none';map.on('move zoom resize zoomend',scheduleClip);map.on('moveend zoomend',()=>{clearTimeout(rebuildTimer);rebuildTimer=setTimeout(()=>rebuild(true),180);});load();
})();
